### ISSUE TITLE
parse_func: read help text from annotation (similar to plac) or from docstring

### ISSUE THREAD

**Issue by vanyakosmos** [vanyakosmos/argser#23]
for functions:
```python
def func(a: int, b):
    """
    Command docs

    :param a: attribute description
    :param b: other help message
    :type b: str
    """
call(func)
```

for classes:
```python
class Args:
    """Command docs"""
    
    class Sub:
        """sub command doc"""
```

**Comment by thautwarm** [comment]
Any progress?

**Comment by vanyakosmos** [comment]
I was distracted by other projects and totally forgot about `argser`. Also I am surprised that someone (except for me) is using it :)

I will try to implement this feature soon.

**Comment by thautwarm** [comment]
That's okay.

> Also I am surprised that someone (except for me) is using it :)

What the hell? Do you know you're making the BEST python argument parsing library so far? Although it'd be a little difficult to sell a package, but you should never judge yourself from unconcious people's ignorance.

**Comment by thautwarm** [comment]
If I can star more I want to give you 10k stars.
